### PR TITLE
Add support for itinerary price metrics API

### PR DESCRIPTION
**Pull request by developius**
## Changes for this pull request

This PR adds support for the [Flight Price Analysis API](https://developers.amadeus.com/blog/inroducing-flight-price-analysis-historical-flight-price-data).

### CODE REVIEW

**Comment by developius** [comment]
Looks like there's a mismatch between the [Gemfile's `bundle` version (2.1.2)](https://github.com/amadeus4dev/amadeus-ruby/blob/master/amadeus.gemspec#L32) and the one being used by Travis (2.2.14) which is causing the build to fail.

**Comment by anthonyroux** [comment]
Approved!

I have fixed the issue with the version of bundle and tested your code.

Thank you very much for your contribution!

**Comment by anthonyroux** [comment]
New version of the gem published ([2.5.0](https://rubygems.org/gems/amadeus)) including your contribution (credits added to the changelog file and the GitHub release).

Thanks again :)

**Comment by developius** [comment]
Cheers @anthonyroux 🚀

**Pull request merged**
